import {expect,test} from '@playwright/test';
import {resetAuth,signIn} from '../helpers/sign-in';
import {TestStepHelper} from '../helpers/test-step-helper';
test('generation, feedback, exact approval and copy survive reload',async({page,context,request},testInfo)=>{
  await resetAuth(request);await page.goto('/');await signIn(page,context);
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Show us the item'})).toBeVisible();
  const itemUrl=page.url();
  await expect(page.getByRole('button',{name:'Create my draft'})).toBeDisabled();
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.getByRole('button',{name:'Create my draft'}).click();
  const steps=new TestStepHelper(page,testInfo);steps.setMetadata('Generation, feedback and approval','Photo-first generation with language feedback and exact approval. AI transport is isolated in the test process.');
  await expect(page.locator('main[data-workflow]')).toHaveAttribute('data-workflow',/generating|reviewing/);
  await expect(page.getByRole('heading',{name:'Listing proposal',exact:true})).toBeVisible();
  await page.getByLabel('Title',{exact:true}).fill('Checked green jacket');
  await page.getByLabel('Description',{exact:true}).fill('Checked condition and label. Measurements available on request.');
  await page.getByLabel('Description',{exact:true}).blur();
  await page.getByLabel('Listing price in GBP').fill('42.50');
  await page.getByLabel('Listing price in GBP').blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.getByLabel('Language feedback',{exact:true}).fill('Use plain, concise language.');
  await page.getByRole('button',{name:'Apply feedback',exact:true}).click();
  await expect(page.getByText('Wording updated. Feedback remembered.',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Description',{exact:true})).toHaveValue(/Revised wording/);
  await expect(page.getByLabel('Listing price in GBP')).toHaveValue('42.50');
  const feedbackTarget=await page.locator('.language-feedback summary').boundingBox();
  expect(feedbackTarget?.height).toBeGreaterThanOrEqual(44);
  await steps.step('review',{description:'Language feedback beside the editable draft',verifications:[{spec:'Feedback applies to current and future drafts',check:async()=>expect(page.getByText('Applies to this draft and future listings.',{exact:true})).toBeVisible()}]});
  await page.getByRole('button',{name:/Check size, labels and wear/}).click();
  await expect(page.getByRole('heading',{name:'Your photo evidence'})).toBeVisible();
  await steps.step('evidence',{description:'Observations reference the supplied photo',verifications:[{spec:'Actual observation text is rendered',check:async()=>expect(page.getByText(/Test photo observation/)).toBeVisible()}]});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:/Check size, labels and wear/})).toBeFocused();
  await page.getByLabel('Title',{exact:true}).focus();
  await page.emulateMedia({colorScheme:testInfo.project.use.colorScheme==='dark'?'light':'dark'});
  await expect(page.getByLabel('Title',{exact:true})).toBeFocused();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Checked green jacket');
  await page.emulateMedia({colorScheme:testInfo.project.use.colorScheme});
  const other=await context.newPage();
  await other.goto(itemUrl);
  await expect(other.getByRole('heading',{name:'Listing proposal',exact:true})).toBeVisible();
  await other.getByLabel('Title',{exact:true}).fill('Another tab title');
  await other.getByLabel('Title',{exact:true}).blur();
  await expect(other.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Checked green jacket');
  await page.getByLabel('Title',{exact:true}).fill('Local stale title');
  await expect(page.getByRole('button',{name:'Review latest version',exact:true})).toBeVisible();
  await other.close();
  await page.getByRole('button',{name:'Review latest version',exact:true}).click();
  await page.getByRole('button',{name:'Use latest version',exact:true}).click();
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Another tab title');
  await page.getByLabel('Title',{exact:true}).fill('Checked green jacket');
  await page.getByLabel('Title',{exact:true}).blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await context.setOffline(true);
  await page.getByRole('button',{name:'Approve listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Approval pending',exact:true})).toBeVisible();
  await steps.step('approval-pending',{description:'Offline approval preserves the immutable submitted version',verifications:[{spec:'Copy waits for confirmed approval',check:async()=>expect(page.getByRole('button',{name:'Copy listing',exact:true})).toHaveCount(0)}]});
  await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Ready to copy'})).toBeVisible();
  await page.reload();await expect(page.getByRole('heading',{name:'Ready to copy'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Checked green jacket'})).toBeVisible();
  await expect(page.getByText('£42.50',{exact:true})).toBeVisible();
  await steps.step('approved',{description:'Reload restores the approved copy and exact price',verifications:[{spec:'The approved version is read-only',check:async()=>expect(page.getByLabel('Title',{exact:true})).toHaveCount(0)}]});
  await page.getByRole('button',{name:'View full listing'}).click();
  await expect(page.getByLabel('Approved listing text')).toHaveValue(/Checked green jacket/);
  await expect(page.getByLabel('Approved listing text')).toHaveValue(/£42.50/);
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('blocked'))},configurable:true}));
  await page.getByRole('button',{name:'Copy listing',exact:true}).click();
  await expect(page.getByRole('button',{name:'Select listing text',exact:true})).toBeVisible();
  steps.generateDocs();
});

test('offline feedback survives closing the page, is remembered on the next draft, and can be forgotten',async({page,context,request})=>{
  await resetAuth(request);await page.goto('/');await signIn(page,context);
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.getByRole('button',{name:'Create my draft'}).click();
  await expect(page.getByRole('heading',{name:'Listing proposal',exact:true})).toBeVisible();
  const url=page.url();
  await context.setOffline(true);
  await page.getByLabel('Language feedback',{exact:true}).fill('Keep descriptions short.');
  await page.getByRole('button',{name:'Apply feedback',exact:true}).click();
  await expect(page.getByText(/Feedback saved on this phone/)).toBeVisible();
  await page.close();await context.setOffline(false);
  const resumed=await context.newPage();await resumed.goto(url);
  await expect(resumed.getByText('Wording updated. Feedback remembered.',{exact:true})).toBeVisible();
  await resumed.getByRole('link',{name:'Your listings',exact:true}).click();
  await resumed.getByRole('link',{name:'New listing',exact:true}).click();
  await resumed.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(resumed.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await resumed.getByRole('button',{name:'Create my draft'}).click();
  await expect(resumed.getByLabel('Description',{exact:true})).toHaveValue('Draft with remembered feedback.');
  await resumed.getByText('Remembered feedback',{exact:true}).click();
  await resumed.getByRole('button',{name:'Forget instruction: Keep descriptions short.',exact:true}).click();
  await expect(resumed.getByText('Remembered feedback',{exact:true})).toHaveCount(0);
  await expect(resumed.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await resumed.reload();await expect(resumed.getByText('Remembered feedback',{exact:true})).toHaveCount(0);
});
