import {expect,test} from '@playwright/test';
import {resetAuth,signIn} from '../helpers/sign-in';
import {TestStepHelper} from '../helpers/test-step-helper';
test('examples, sample generation, evidence, exact approval and copy survive reload',async({page,context,request},testInfo)=>{
  await resetAuth(request);await page.goto('/');await signIn(page,context);
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Show us the item'})).toBeVisible();
  const itemUrl=page.url();
  await expect(page.getByRole('button',{name:'Create my draft'})).toBeDisabled();
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.getByRole('button',{name:'Create my draft'}).click();
  await expect(page.getByRole('heading',{name:'Make it sound like you'})).toBeVisible();
  await page.getByRole('button',{name:'Learn my style'}).click();
  await expect(page.getByText('Add the listing title.',{exact:true})).toBeVisible();
  await page.getByLabel('Title',{exact:true}).fill('Oatmeal wool jumper');
  await page.getByLabel('Description',{exact:true}).fill('Lovely soft knit with a relaxed fit. A little bobbling at the cuffs, shown in the photos.');
  await page.getByLabel('Description',{exact:true}).blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  const steps=new TestStepHelper(page,testInfo);steps.setMetadata('Examples, generation and approval','A labelled sample journey backed by durable Functions and owner-scoped events.');
  await steps.step('examples',{description:'Paste one complete example',verifications:[{spec:'The original item return path is retained',check:async()=>expect(page.getByRole('link',{name:'Back to photos',exact:true})).toHaveAttribute('href',new URL(itemUrl).pathname+'?view=photos')}]});
  await page.getByRole('button',{name:'Learn my style'}).click();
  await expect(page.getByRole('link',{name:'Back to photos',exact:true}).first()).toBeVisible();
  await expect(page.getByRole('heading',{name:'Your examples are ready'})).toBeVisible();
  await steps.step('style-ready',{description:'Traceable sample profile with explicit return',verifications:[{spec:'The seller chooses when to return to photos',check:async()=>expect(page.getByRole('link',{name:'Continue to photos'})).toBeVisible()}]});
  await page.getByRole('link',{name:'Continue to photos'}).click();
  await page.getByRole('button',{name:'Create my draft'}).click();
  await expect(page.locator('main[data-workflow]')).toHaveAttribute('data-workflow',/generating|reviewing/);
  await expect(page.getByRole('heading',{name:'Listing proposal',exact:true})).toBeVisible();
  await page.getByLabel('Title',{exact:true}).fill('Checked green jacket');
  await page.getByLabel('Description',{exact:true}).fill('Checked condition and label. Measurements available on request.');
  await page.getByLabel('Description',{exact:true}).blur();
  await page.getByLabel('Listing price in GBP').fill('42.50');
  await page.getByLabel('Listing price in GBP').blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await steps.step('review',{description:'Editable proposal with honest price limitations',verifications:[{spec:'Sale estimates are unavailable without market evidence',check:async()=>expect(page.getByText('Expected sale range unavailable',{exact:true})).toBeVisible()}]});
  await page.getByRole('button',{name:/Price evidence No asking/}).click();
  await expect(page.getByRole('heading',{name:'Evidence unavailable'})).toBeVisible();
  await steps.step('evidence',{description:'Missing market evidence is explicit',verifications:[{spec:'No invented comparables appear',check:async()=>expect(page.getByText('Sample price · £48 is illustrative.',{exact:true})).toBeVisible()}]});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:/Price evidence No asking/})).toBeFocused();
  await expect(page.getByLabel('Listing price in GBP')).toHaveValue('42.50');
  await page.getByLabel('Title',{exact:true}).focus();
  await page.emulateMedia({colorScheme:testInfo.project.use.colorScheme==='dark'?'light':'dark'});
  await expect(page.getByLabel('Title',{exact:true})).toBeFocused();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Checked green jacket');
  await page.emulateMedia({colorScheme:testInfo.project.use.colorScheme});
  const other=await context.newPage();
  await other.goto(itemUrl);
  await expect(other.getByRole('heading',{name:'Listing proposal',exact:true})).toBeVisible();
  await other.getByLabel('Title',{exact:true}).fill('Another tab title');
  await other.getByLabel('Title',{exact:true}).blur();
  await expect(other.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Checked green jacket');
  await page.getByLabel('Title',{exact:true}).fill('Local stale title');
  await expect(page.getByRole('button',{name:'Review latest version',exact:true})).toBeVisible();
  await other.close();
  await page.getByRole('button',{name:'Review latest version',exact:true}).click();
  await page.getByRole('button',{name:'Use latest version',exact:true}).click();
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Another tab title');
  await page.getByLabel('Title',{exact:true}).fill('Checked green jacket');
  await page.getByLabel('Title',{exact:true}).blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await context.setOffline(true);
  await page.getByRole('button',{name:'Approve listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Approval pending',exact:true})).toBeVisible();
  await steps.step('approval-pending',{description:'Offline approval preserves the immutable submitted version',verifications:[{spec:'Copy waits for confirmed approval',check:async()=>expect(page.getByRole('button',{name:'Copy listing',exact:true})).toHaveCount(0)}]});
  await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Ready to copy'})).toBeVisible();
  await page.reload();await expect(page.getByRole('heading',{name:'Ready to copy'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Checked green jacket'})).toBeVisible();
  await expect(page.getByText('£42.50',{exact:true})).toBeVisible();
  await steps.step('approved',{description:'Reload restores the approved copy and exact price',verifications:[{spec:'The approved version is read-only',check:async()=>expect(page.getByLabel('Title',{exact:true})).toHaveCount(0)}]});
  await page.getByRole('button',{name:'View full listing'}).click();
  await expect(page.getByLabel('Approved listing text')).toHaveValue(/Checked green jacket/);
  await expect(page.getByLabel('Approved listing text')).toHaveValue(/£42.50/);
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('blocked'))},configurable:true}));
  await page.getByRole('button',{name:'Copy listing',exact:true}).click();
  await expect(page.getByRole('button',{name:'Select listing text',exact:true})).toBeVisible();
  steps.generateDocs();
});

test('partial examples, removal undo and offline learning remain recoverable',async({page,context,request})=>{
  await resetAuth(request);await page.goto('/');await signIn(page,context);
  await page.getByRole('button',{name:'Your account',exact:true}).click();
  await page.getByRole('button',{name:/Your listing style/}).click();
  await page.getByLabel('Title',{exact:true}).fill('My saved partial example');
  await page.getByLabel('Title',{exact:true}).blur();
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.reload();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('My saved partial example');
  await page.getByLabel('Title',{exact:true}).fill('First tab example');
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  const other=await context.newPage();await other.goto('/style');
  await expect(other.getByLabel('Title',{exact:true})).toHaveValue('First tab example');
  await other.getByLabel('Title',{exact:true}).fill('Other tab example');
  await expect(other.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await page.getByLabel('Title',{exact:true}).fill('Stale example');
  await expect(page.getByRole('button',{name:'Review latest version',exact:true})).toBeVisible();
  await other.close();
  await page.getByRole('button',{name:'Review latest version',exact:true}).click();
  await page.getByRole('button',{name:'Use latest version',exact:true}).click();
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Other tab example');
  await page.getByLabel('Title',{exact:true}).fill('My saved partial example');
  await expect(page.locator('main[data-sync]')).toHaveAttribute('data-sync','synced');
  await context.setOffline(true);
  await page.getByLabel('Description',{exact:true}).fill('A soft cotton shirt with an easy fit.');
  await page.getByRole('button',{name:'Add another example'}).click();
  await page.getByRole('button',{name:'Remove example 2'}).click();
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Example 2',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Remove example 2'}).click();
  await page.getByRole('button',{name:'Learn my style'}).click();
  await expect(page.getByText('Will start when connected',{exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Back to account',exact:true}).first()).toBeVisible();
  await page.close();await context.setOffline(false);
  const resumed=await context.newPage();await resumed.goto('/style?view=learning');
  await expect(resumed.getByRole('heading',{name:'Your examples are ready'})).toBeVisible();
  await expect(resumed.getByText('My saved partial example',{exact:true})).toBeVisible();
  await resumed.getByRole('link',{name:'Back to account',exact:true}).last().click();
  await expect(resumed.getByRole('dialog',{name:'Your account',exact:true})).toBeVisible();
});
