import { expect, test } from '@playwright/test';
import { TestStepHelper } from '../helpers/test-step-helper';
import { resetAuth, signIn } from '../helpers/sign-in';

test('photo entry follows the approved flow and resumes the saved item', async ({ page, context, request }, testInfo) => {
  await resetAuth(request); await page.goto('/'); await signIn(page, context);
  const steps=new TestStepHelper(page,testInfo);
  steps.setMetadata('Listings and photo entry','Start a listing with photos and optional context, persisted to the backend.');
  await steps.step('listings',{description:'Start a new listing without a name form',verifications:[{spec:'New listing opens the photo flow',check:async()=>expect(page.getByRole('link',{name:'New listing',exact:true})).toBeVisible()}]});
  await page.getByRole('link', {name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading', { name: 'Show us the item' })).toBeVisible();
  await expect(page.getByLabel('Draft name')).toHaveCount(0);
  const url=page.url();
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.getByLabel('Anything else?').fill('Rare 1990s piece, fits oversized');
  await page.getByLabel('Anything else?').blur();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Anything else?')).toHaveValue('Rare 1990s piece, fits oversized');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await steps.step('photo-entry',{description:'Photo and context restored after reload',verifications:[{spec:'The approved step header is visible',check:async()=>expect(page.getByText('1 of 3 · Add photos',{exact:true})).toBeVisible()},{spec:'The photo opens for inspection',check:async()=>expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled()}]});steps.generateDocs();
  await page.getByLabel('Anything else?').focus();
  await page.emulateMedia({colorScheme:testInfo.project.use.colorScheme==='dark'?'light':'dark'});
  await expect(page.getByLabel('Anything else?')).toBeFocused();
  await expect(page.getByLabel('Anything else?')).toHaveValue('Rare 1990s piece, fits oversized');
  expect(page.url()).toBe(url);
  await page.getByRole('button',{name:'Inspect photo 1'}).click();
  await expect(page.getByRole('dialog').getByAltText('Item photo 1')).toBeVisible();
  await page.getByRole('button',{name:'Close photo',exact:true}).click();
  await page.getByRole('button',{name:'Your account'}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await expect(page.getByLabel('Anything else?')).toHaveCount(0);
  await signIn(page,context,'second.seller@example.test','Second Seller');
  await expect(page.getByRole('heading',{name:'Item unavailable'})).toBeVisible();
});

test('photo controls reorder, remove and reject unsupported files', async ({page,context,request}) => {
  await resetAuth(request);await page.goto('/');await signIn(page,context); await page.getByRole('link', {name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Show us the item'})).toBeVisible();
  await page.getByLabel('Choose item photos').setInputFiles(['static/images/wardrobe.png','static/images/wardrobe.png']);
  await expect(page.getByRole('button',{name:'Inspect photo 2'})).toBeEnabled();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Inspect photo 1'}).click();
  await page.getByRole('button',{name:'Move later'}).click();
  await expect(page.getByText('Photo 2 of 2',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Replace photo'}).click();
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Inspect photo 2'}).click();
  await expect(page.getByText('Photo 2 of 2',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Remove photo'}).click();
  await expect(page.getByRole('button',{name:'Inspect photo 2'})).toHaveCount(0);
  await page.reload();await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await page.getByLabel('Choose item photos').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not a photo')});
  await expect(page.getByRole('alert')).toContainText('Choose a JPEG');
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
});

test('HEIC original has a readable preview after reload', async ({page,context,request}) => {
  await resetAuth(request); await page.goto('/'); await signIn(page,context); await page.getByRole('link', {name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Show us the item'})).toBeVisible();
  await page.getByLabel('Choose item photos').setInputFiles('tests/fixtures/sample.heic');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await page.getByRole('button',{name:'Inspect photo 1'}).click();
  await expect.poll(() => page.getByRole('dialog').getByAltText('Item photo 1').evaluate((img: HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);
});

test('offline edits and navigation apply immediately and sync after reconnect', async ({page,context,request}) => {
  await resetAuth(request); await page.goto('/'); await signIn(page,context);
  await expect(page.getByRole('heading',{name:'Your listings'})).toBeVisible();
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  const first = page.url();
  await context.setOffline(true);
  await page.getByLabel('Anything else?').fill('Written offline');
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByAltText('Selected item',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Add photo',exact:true})).toBeEnabled();
  await page.getByRole('link',{name:'Your listings',exact:true}).click();
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Show us the item'})).toBeVisible();
  expect(page.url()).not.toBe(first);
  await page.getByLabel('Anything else?').fill('Second offline listing');
  await context.setOffline(false);
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Anything else?')).toHaveValue('Second offline listing');
  await page.goto(first);
  await expect(page.getByLabel('Anything else?')).toHaveValue('Written offline');
  await expect(page.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
});

test('selected photo bytes recover when the page closes before upload', async ({page,context,request}) => {
  await resetAuth(request); await page.goto('/'); await signIn(page,context);
  await page.getByRole('link',{name:'New listing',exact:true}).click();
  await expect(page.getByText('Saved',{exact:true})).toBeVisible();
  const url=page.url();
  await context.setOffline(true);
  await page.getByLabel('Choose item photos').setInputFiles('static/images/wardrobe.png');
  await expect(page.getByAltText('Selected item',{exact:true})).toBeVisible();
  await page.close();
  await context.setOffline(false);
  const resumed=await context.newPage();await resumed.goto(url);
  await expect(resumed.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
  await expect(resumed.getByText('Saved',{exact:true})).toBeVisible();
  await resumed.reload();
  await expect(resumed.getByRole('button',{name:'Inspect photo 1'})).toBeEnabled();
});
